package com.southwind.frigga.dal.mybatis.mapper;

import com.southwind.frigga.dal.mybatis.model.AdInfo;
import com.southwind.frigga.dal.mybatis.model.AdInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int countByExample(AdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int deleteByExample(AdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int insert(AdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int insertSelective(AdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     * @param length 
     * @param start 
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    List<AdInfo> selectByExample(@Param("example") AdInfoExample example, @Param("start") int start, @Param("length") int length);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    AdInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") AdInfo record, @Param("example") AdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByExample(@Param("record") AdInfo record, @Param("example") AdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(AdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByPrimaryKey(AdInfo record);
}