package com.southwind.frigga.dal.mybatis.mapper;

import com.southwind.frigga.dal.mybatis.model.AdSpreadDay;
import com.southwind.frigga.dal.mybatis.model.AdSpreadDayExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AdSpreadDayMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int countByExample(AdSpreadDayExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByExample(AdSpreadDayExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByPrimaryKey(Long id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insert(AdSpreadDay record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insertSelective(AdSpreadDay record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @param qdid 
	 * @param length 
	 * @param start 
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	List<AdSpreadDay> selectByExample(@Param("example") AdSpreadDayExample example, @Param("qdid") long qdid, @Param("start") int start, @Param("length") int length);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	AdSpreadDay selectByPrimaryKey(Long id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AdSpreadDay record,
			@Param("example") AdSpreadDayExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExample(@Param("record") AdSpreadDay record,
			@Param("example") AdSpreadDayExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKeySelective(AdSpreadDay record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread_day
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKey(AdSpreadDay record);


	/**
	 * @param spreadId
	 * @param spreadDate
	 * @return 
	 * @exception 
	 * @since  1.0.0
	 */
	
	AdSpreadDay getDataForDay(@Param("spreadId") long spreadId, @Param("spreadDate") String spreadDate);

	
	/**
	 * @param spreadId
	 * @return 
	 * @exception 
	 * @since  1.0.0
	 */
	Integer selectSumBySpreadId(long spreadId);
}