package com.southwind.frigga.dal.mybatis.mapper;

import com.southwind.frigga.dal.mybatis.model.AdSpread;
import com.southwind.frigga.dal.mybatis.model.AdSpreadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdSpreadMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int countByExample(AdSpreadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByExample(AdSpreadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insert(AdSpread record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insertSelective(AdSpread record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @param length 
	 * @param start 
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	List<AdSpread> selectByExample(@Param("example") AdSpreadExample example, @Param("start") int start, @Param("length") int length);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	AdSpread selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AdSpread record,
			@Param("example") AdSpreadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExample(@Param("record") AdSpread record,
			@Param("example") AdSpreadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKeySelective(AdSpread record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_spread
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKey(AdSpread record);
}