package com.southwind.frigga.dal.mybatis.mapper;

import com.southwind.frigga.dal.mybatis.model.AdSpread;
import com.southwind.frigga.dal.mybatis.model.AdSpreadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdSpreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int countByExample(AdSpreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int deleteByExample(AdSpreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int insert(AdSpread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int insertSelective(AdSpread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    List<AdSpread> selectByExample(AdSpreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    AdSpread selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") AdSpread record, @Param("example") AdSpreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByExample(@Param("record") AdSpread record, @Param("example") AdSpreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(AdSpread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByPrimaryKey(AdSpread record);
}