package com.southwind.frigga.dal.mybatis.mapper;

import com.southwind.frigga.dal.mybatis.model.ChannelUser;
import com.southwind.frigga.dal.mybatis.model.ChannelUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int countByExample(ChannelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByExample(ChannelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insert(ChannelUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insertSelective(ChannelUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @param length 
	 * @param start 
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	List<ChannelUser> selectByExample(@Param("example") ChannelUserExample example, @Param("start") int start, @Param("length") int length);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	ChannelUser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExampleSelective(@Param("record") ChannelUser record,
			@Param("example") ChannelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExample(@Param("record") ChannelUser record,
			@Param("example") ChannelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKeySelective(ChannelUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table channel_user
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKey(ChannelUser record);
}