package com.southwind.frigga.dal.mybatis.mapper;

import com.southwind.frigga.dal.mybatis.model.ChannelUser;
import com.southwind.frigga.dal.mybatis.model.ChannelUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int countByExample(ChannelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int deleteByExample(ChannelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int insert(ChannelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int insertSelective(ChannelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    List<ChannelUser> selectByExample(ChannelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    ChannelUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") ChannelUser record, @Param("example") ChannelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByExample(@Param("record") ChannelUser record, @Param("example") ChannelUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(ChannelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    int updateByPrimaryKey(ChannelUser record);
}