package com.southwind.frigga.dal.mybatis.mapper;

import com.southwind.frigga.dal.mybatis.model.Revenue;
import com.southwind.frigga.dal.mybatis.model.RevenueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RevenueMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int countByExample(RevenueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByExample(RevenueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insert(Revenue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int insertSelective(Revenue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	List<Revenue> selectByExample(RevenueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	Revenue selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Revenue record,
			@Param("example") RevenueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByExample(@Param("record") Revenue record,
			@Param("example") RevenueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKeySelective(Revenue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	int updateByPrimaryKey(Revenue record);
}