package com.southwind.frigga.dal.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class AdInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public AdInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAdNameIsNull() {
            addCriterion("ad_name is null");
            return (Criteria) this;
        }

        public Criteria andAdNameIsNotNull() {
            addCriterion("ad_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdNameEqualTo(String value) {
            addCriterion("ad_name =", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameNotEqualTo(String value) {
            addCriterion("ad_name <>", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameGreaterThan(String value) {
            addCriterion("ad_name >", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameGreaterThanOrEqualTo(String value) {
            addCriterion("ad_name >=", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameLessThan(String value) {
            addCriterion("ad_name <", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameLessThanOrEqualTo(String value) {
            addCriterion("ad_name <=", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameLike(String value) {
            addCriterion("ad_name like", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameNotLike(String value) {
            addCriterion("ad_name not like", value, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameIn(List<String> values) {
            addCriterion("ad_name in", values, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameNotIn(List<String> values) {
            addCriterion("ad_name not in", values, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameBetween(String value1, String value2) {
            addCriterion("ad_name between", value1, value2, "adName");
            return (Criteria) this;
        }

        public Criteria andAdNameNotBetween(String value1, String value2) {
            addCriterion("ad_name not between", value1, value2, "adName");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIsNull() {
            addCriterion("advertiser is null");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIsNotNull() {
            addCriterion("advertiser is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertiserEqualTo(String value) {
            addCriterion("advertiser =", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotEqualTo(String value) {
            addCriterion("advertiser <>", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserGreaterThan(String value) {
            addCriterion("advertiser >", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserGreaterThanOrEqualTo(String value) {
            addCriterion("advertiser >=", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserLessThan(String value) {
            addCriterion("advertiser <", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserLessThanOrEqualTo(String value) {
            addCriterion("advertiser <=", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserLike(String value) {
            addCriterion("advertiser like", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotLike(String value) {
            addCriterion("advertiser not like", value, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIn(List<String> values) {
            addCriterion("advertiser in", values, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotIn(List<String> values) {
            addCriterion("advertiser not in", values, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserBetween(String value1, String value2) {
            addCriterion("advertiser between", value1, value2, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdvertiserNotBetween(String value1, String value2) {
            addCriterion("advertiser not between", value1, value2, "advertiser");
            return (Criteria) this;
        }

        public Criteria andAdTypeIsNull() {
            addCriterion("ad_type is null");
            return (Criteria) this;
        }

        public Criteria andAdTypeIsNotNull() {
            addCriterion("ad_type is not null");
            return (Criteria) this;
        }

        public Criteria andAdTypeEqualTo(String value) {
            addCriterion("ad_type =", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeNotEqualTo(String value) {
            addCriterion("ad_type <>", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeGreaterThan(String value) {
            addCriterion("ad_type >", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ad_type >=", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeLessThan(String value) {
            addCriterion("ad_type <", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeLessThanOrEqualTo(String value) {
            addCriterion("ad_type <=", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeLike(String value) {
            addCriterion("ad_type like", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeNotLike(String value) {
            addCriterion("ad_type not like", value, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeIn(List<String> values) {
            addCriterion("ad_type in", values, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeNotIn(List<String> values) {
            addCriterion("ad_type not in", values, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeBetween(String value1, String value2) {
            addCriterion("ad_type between", value1, value2, "adType");
            return (Criteria) this;
        }

        public Criteria andAdTypeNotBetween(String value1, String value2) {
            addCriterion("ad_type not between", value1, value2, "adType");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNull() {
            addCriterion("unit_price is null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNotNull() {
            addCriterion("unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceEqualTo(Double value) {
            addCriterion("unit_price =", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotEqualTo(Double value) {
            addCriterion("unit_price <>", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThan(Double value) {
            addCriterion("unit_price >", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("unit_price >=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThan(Double value) {
            addCriterion("unit_price <", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThanOrEqualTo(Double value) {
            addCriterion("unit_price <=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIn(List<Double> values) {
            addCriterion("unit_price in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotIn(List<Double> values) {
            addCriterion("unit_price not in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceBetween(Double value1, Double value2) {
            addCriterion("unit_price between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotBetween(Double value1, Double value2) {
            addCriterion("unit_price not between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeIsNull() {
            addCriterion("shelves_time is null");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeIsNotNull() {
            addCriterion("shelves_time is not null");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeEqualTo(String value) {
            addCriterion("shelves_time =", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeNotEqualTo(String value) {
            addCriterion("shelves_time <>", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeGreaterThan(String value) {
            addCriterion("shelves_time >", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeGreaterThanOrEqualTo(String value) {
            addCriterion("shelves_time >=", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeLessThan(String value) {
            addCriterion("shelves_time <", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeLessThanOrEqualTo(String value) {
            addCriterion("shelves_time <=", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeLike(String value) {
            addCriterion("shelves_time like", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeNotLike(String value) {
            addCriterion("shelves_time not like", value, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeIn(List<String> values) {
            addCriterion("shelves_time in", values, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeNotIn(List<String> values) {
            addCriterion("shelves_time not in", values, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeBetween(String value1, String value2) {
            addCriterion("shelves_time between", value1, value2, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andShelvesTimeNotBetween(String value1, String value2) {
            addCriterion("shelves_time not between", value1, value2, "shelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeIsNull() {
            addCriterion("off_shelves_time is null");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeIsNotNull() {
            addCriterion("off_shelves_time is not null");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeEqualTo(String value) {
            addCriterion("off_shelves_time =", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeNotEqualTo(String value) {
            addCriterion("off_shelves_time <>", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeGreaterThan(String value) {
            addCriterion("off_shelves_time >", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeGreaterThanOrEqualTo(String value) {
            addCriterion("off_shelves_time >=", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeLessThan(String value) {
            addCriterion("off_shelves_time <", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeLessThanOrEqualTo(String value) {
            addCriterion("off_shelves_time <=", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeLike(String value) {
            addCriterion("off_shelves_time like", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeNotLike(String value) {
            addCriterion("off_shelves_time not like", value, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeIn(List<String> values) {
            addCriterion("off_shelves_time in", values, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeNotIn(List<String> values) {
            addCriterion("off_shelves_time not in", values, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeBetween(String value1, String value2) {
            addCriterion("off_shelves_time between", value1, value2, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andOffShelvesTimeNotBetween(String value1, String value2) {
            addCriterion("off_shelves_time not between", value1, value2, "offShelvesTime");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginIsNull() {
            addCriterion("ad_platform_login is null");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginIsNotNull() {
            addCriterion("ad_platform_login is not null");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginEqualTo(String value) {
            addCriterion("ad_platform_login =", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginNotEqualTo(String value) {
            addCriterion("ad_platform_login <>", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginGreaterThan(String value) {
            addCriterion("ad_platform_login >", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginGreaterThanOrEqualTo(String value) {
            addCriterion("ad_platform_login >=", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginLessThan(String value) {
            addCriterion("ad_platform_login <", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginLessThanOrEqualTo(String value) {
            addCriterion("ad_platform_login <=", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginLike(String value) {
            addCriterion("ad_platform_login like", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginNotLike(String value) {
            addCriterion("ad_platform_login not like", value, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginIn(List<String> values) {
            addCriterion("ad_platform_login in", values, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginNotIn(List<String> values) {
            addCriterion("ad_platform_login not in", values, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginBetween(String value1, String value2) {
            addCriterion("ad_platform_login between", value1, value2, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformLoginNotBetween(String value1, String value2) {
            addCriterion("ad_platform_login not between", value1, value2, "adPlatformLogin");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdIsNull() {
            addCriterion("ad_platform_pwd is null");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdIsNotNull() {
            addCriterion("ad_platform_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdEqualTo(String value) {
            addCriterion("ad_platform_pwd =", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdNotEqualTo(String value) {
            addCriterion("ad_platform_pwd <>", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdGreaterThan(String value) {
            addCriterion("ad_platform_pwd >", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdGreaterThanOrEqualTo(String value) {
            addCriterion("ad_platform_pwd >=", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdLessThan(String value) {
            addCriterion("ad_platform_pwd <", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdLessThanOrEqualTo(String value) {
            addCriterion("ad_platform_pwd <=", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdLike(String value) {
            addCriterion("ad_platform_pwd like", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdNotLike(String value) {
            addCriterion("ad_platform_pwd not like", value, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdIn(List<String> values) {
            addCriterion("ad_platform_pwd in", values, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdNotIn(List<String> values) {
            addCriterion("ad_platform_pwd not in", values, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdBetween(String value1, String value2) {
            addCriterion("ad_platform_pwd between", value1, value2, "adPlatformPwd");
            return (Criteria) this;
        }

        public Criteria andAdPlatformPwdNotBetween(String value1, String value2) {
            addCriterion("ad_platform_pwd not between", value1, value2, "adPlatformPwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_info
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}