package com.southwind.frigga.dal.mybatis.model;

public class AdInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String adName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.advertiser
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String advertiser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_type
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String adType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.unit_price
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Double unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.shelves_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String shelvesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.off_shelves_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String offShelvesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_platform_login
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String adPlatformLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_info.ad_platform_pwd
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String adPlatformPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.id
     *
     * @return the value of ad_info.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.id
     *
     * @param id the value for ad_info.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_name
     *
     * @return the value of ad_info.ad_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_name
     *
     * @param adName the value for ad_info.ad_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setAdName(String adName) {
        this.adName = adName == null ? null : adName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.advertiser
     *
     * @return the value of ad_info.advertiser
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getAdvertiser() {
        return advertiser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.advertiser
     *
     * @param advertiser the value for ad_info.advertiser
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setAdvertiser(String advertiser) {
        this.advertiser = advertiser == null ? null : advertiser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_type
     *
     * @return the value of ad_info.ad_type
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getAdType() {
        return adType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_type
     *
     * @param adType the value for ad_info.ad_type
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setAdType(String adType) {
        this.adType = adType == null ? null : adType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.unit_price
     *
     * @return the value of ad_info.unit_price
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Double getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.unit_price
     *
     * @param unitPrice the value for ad_info.unit_price
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.shelves_time
     *
     * @return the value of ad_info.shelves_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getShelvesTime() {
        return shelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.shelves_time
     *
     * @param shelvesTime the value for ad_info.shelves_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setShelvesTime(String shelvesTime) {
        this.shelvesTime = shelvesTime == null ? null : shelvesTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.off_shelves_time
     *
     * @return the value of ad_info.off_shelves_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getOffShelvesTime() {
        return offShelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.off_shelves_time
     *
     * @param offShelvesTime the value for ad_info.off_shelves_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setOffShelvesTime(String offShelvesTime) {
        this.offShelvesTime = offShelvesTime == null ? null : offShelvesTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_platform_login
     *
     * @return the value of ad_info.ad_platform_login
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getAdPlatformLogin() {
        return adPlatformLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_platform_login
     *
     * @param adPlatformLogin the value for ad_info.ad_platform_login
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setAdPlatformLogin(String adPlatformLogin) {
        this.adPlatformLogin = adPlatformLogin == null ? null : adPlatformLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_info.ad_platform_pwd
     *
     * @return the value of ad_info.ad_platform_pwd
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getAdPlatformPwd() {
        return adPlatformPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_info.ad_platform_pwd
     *
     * @param adPlatformPwd the value for ad_info.ad_platform_pwd
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setAdPlatformPwd(String adPlatformPwd) {
        this.adPlatformPwd = adPlatformPwd == null ? null : adPlatformPwd.trim();
    }
}