package com.southwind.frigga.dal.mybatis.model;

public class AdSpreadDay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread_day.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread_day.spread_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long spreadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread_day.spread_date
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String spreadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread_day.active_revenue
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long activeRevenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread_day.active_expenses
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long activeExpenses;

    
    private Long adId;

    private Long qdId;

    private String packageName;
    
    private Byte rebateSinceFlag;
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread_day.id
     *
     * @return the value of ad_spread_day.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread_day.id
     *
     * @param id the value for ad_spread_day.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread_day.spread_id
     *
     * @return the value of ad_spread_day.spread_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getSpreadId() {
        return spreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread_day.spread_id
     *
     * @param spreadId the value for ad_spread_day.spread_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setSpreadId(Long spreadId) {
        this.spreadId = spreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread_day.spread_date
     *
     * @return the value of ad_spread_day.spread_date
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getSpreadDate() {
        return spreadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread_day.spread_date
     *
     * @param spreadDate the value for ad_spread_day.spread_date
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setSpreadDate(String spreadDate) {
        this.spreadDate = spreadDate == null ? null : spreadDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread_day.active_revenue
     *
     * @return the value of ad_spread_day.active_revenue
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getActiveRevenue() {
        return activeRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread_day.active_revenue
     *
     * @param activeRevenue the value for ad_spread_day.active_revenue
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setActiveRevenue(Long activeRevenue) {
        this.activeRevenue = activeRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread_day.active_expenses
     *
     * @return the value of ad_spread_day.active_expenses
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getActiveExpenses() {
        return activeExpenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread_day.active_expenses
     *
     * @param activeExpenses the value for ad_spread_day.active_expenses
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setActiveExpenses(Long activeExpenses) {
        this.activeExpenses = activeExpenses;
    }

	/**
	 * adId
	 *
	 * @return  the adId
	 * @since   1.0.0
	 */
	
	public Long getAdId() {
		return adId;
	}

	/**
	 * @param adId the adId to set
	 */
	
	public void setAdId(Long adId) {
		this.adId = adId;
	}

	/**
	 * qdId
	 *
	 * @return  the qdId
	 * @since   1.0.0
	 */
	
	public Long getQdId() {
		return qdId;
	}

	/**
	 * @param qdId the qdId to set
	 */
	
	public void setQdId(Long qdId) {
		this.qdId = qdId;
	}

	/**
	 * packageName
	 *
	 * @return  the packageName
	 * @since   1.0.0
	 */
	
	public String getPackageName() {
		return packageName;
	}

	/**
	 * @param packageName the packageName to set
	 */
	
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * rebateSinceFlag
	 *
	 * @return  the rebateSinceFlag
	 * @since   1.0.0
	 */
	
	public Byte getRebateSinceFlag() {
		return rebateSinceFlag;
	}

	/**
	 * @param rebateSinceFlag the rebateSinceFlag to set
	 */
	
	public void setRebateSinceFlag(Byte rebateSinceFlag) {
		this.rebateSinceFlag = rebateSinceFlag;
	}
    
    
    
}