package com.southwind.frigga.dal.mybatis.model;

public class AdSpread {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.ad_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.qd_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long qdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.package_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.download_url
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.rebate_prop
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Integer rebateProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.rebate_since
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Integer rebateSince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_spread.rebate_since_flag
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Byte rebateSinceFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.id
     *
     * @return the value of ad_spread.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.id
     *
     * @param id the value for ad_spread.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.ad_id
     *
     * @return the value of ad_spread.ad_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.ad_id
     *
     * @param adId the value for ad_spread.ad_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setAdId(Long adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.qd_id
     *
     * @return the value of ad_spread.qd_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getQdId() {
        return qdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.qd_id
     *
     * @param qdId the value for ad_spread.qd_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setQdId(Long qdId) {
        this.qdId = qdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.package_name
     *
     * @return the value of ad_spread.package_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.package_name
     *
     * @param packageName the value for ad_spread.package_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.download_url
     *
     * @return the value of ad_spread.download_url
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.download_url
     *
     * @param downloadUrl the value for ad_spread.download_url
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.rebate_prop
     *
     * @return the value of ad_spread.rebate_prop
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Integer getRebateProp() {
        return rebateProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.rebate_prop
     *
     * @param rebateProp the value for ad_spread.rebate_prop
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setRebateProp(Integer rebateProp) {
        this.rebateProp = rebateProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.rebate_since
     *
     * @return the value of ad_spread.rebate_since
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Integer getRebateSince() {
        return rebateSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.rebate_since
     *
     * @param rebateSince the value for ad_spread.rebate_since
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setRebateSince(Integer rebateSince) {
        this.rebateSince = rebateSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_spread.rebate_since_flag
     *
     * @return the value of ad_spread.rebate_since_flag
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Byte getRebateSinceFlag() {
        return rebateSinceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_spread.rebate_since_flag
     *
     * @param rebateSinceFlag the value for ad_spread.rebate_since_flag
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setRebateSinceFlag(Byte rebateSinceFlag) {
        this.rebateSinceFlag = rebateSinceFlag;
    }
}