package com.southwind.frigga.dal.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class AdSpreadDayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public AdSpreadDayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSpreadIdIsNull() {
            addCriterion("spread_id is null");
            return (Criteria) this;
        }

        public Criteria andSpreadIdIsNotNull() {
            addCriterion("spread_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadIdEqualTo(Long value) {
            addCriterion("spread_id =", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdNotEqualTo(Long value) {
            addCriterion("spread_id <>", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdGreaterThan(Long value) {
            addCriterion("spread_id >", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdGreaterThanOrEqualTo(Long value) {
            addCriterion("spread_id >=", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdLessThan(Long value) {
            addCriterion("spread_id <", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdLessThanOrEqualTo(Long value) {
            addCriterion("spread_id <=", value, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdIn(List<Long> values) {
            addCriterion("spread_id in", values, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdNotIn(List<Long> values) {
            addCriterion("spread_id not in", values, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdBetween(Long value1, Long value2) {
            addCriterion("spread_id between", value1, value2, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadIdNotBetween(Long value1, Long value2) {
            addCriterion("spread_id not between", value1, value2, "spreadId");
            return (Criteria) this;
        }

        public Criteria andSpreadDateIsNull() {
            addCriterion("spread_date is null");
            return (Criteria) this;
        }

        public Criteria andSpreadDateIsNotNull() {
            addCriterion("spread_date is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadDateEqualTo(String value) {
            addCriterion("spread_date =", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateNotEqualTo(String value) {
            addCriterion("spread_date <>", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateGreaterThan(String value) {
            addCriterion("spread_date >", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateGreaterThanOrEqualTo(String value) {
            addCriterion("spread_date >=", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateLessThan(String value) {
            addCriterion("spread_date <", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateLessThanOrEqualTo(String value) {
            addCriterion("spread_date <=", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateLike(String value) {
            addCriterion("spread_date like", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateNotLike(String value) {
            addCriterion("spread_date not like", value, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateIn(List<String> values) {
            addCriterion("spread_date in", values, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateNotIn(List<String> values) {
            addCriterion("spread_date not in", values, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateBetween(String value1, String value2) {
            addCriterion("spread_date between", value1, value2, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andSpreadDateNotBetween(String value1, String value2) {
            addCriterion("spread_date not between", value1, value2, "spreadDate");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueIsNull() {
            addCriterion("active_revenue is null");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueIsNotNull() {
            addCriterion("active_revenue is not null");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueEqualTo(Long value) {
            addCriterion("active_revenue =", value, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueNotEqualTo(Long value) {
            addCriterion("active_revenue <>", value, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueGreaterThan(Long value) {
            addCriterion("active_revenue >", value, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueGreaterThanOrEqualTo(Long value) {
            addCriterion("active_revenue >=", value, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueLessThan(Long value) {
            addCriterion("active_revenue <", value, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueLessThanOrEqualTo(Long value) {
            addCriterion("active_revenue <=", value, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueIn(List<Long> values) {
            addCriterion("active_revenue in", values, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueNotIn(List<Long> values) {
            addCriterion("active_revenue not in", values, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueBetween(Long value1, Long value2) {
            addCriterion("active_revenue between", value1, value2, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveRevenueNotBetween(Long value1, Long value2) {
            addCriterion("active_revenue not between", value1, value2, "activeRevenue");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesIsNull() {
            addCriterion("active_expenses is null");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesIsNotNull() {
            addCriterion("active_expenses is not null");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesEqualTo(Long value) {
            addCriterion("active_expenses =", value, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesNotEqualTo(Long value) {
            addCriterion("active_expenses <>", value, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesGreaterThan(Long value) {
            addCriterion("active_expenses >", value, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesGreaterThanOrEqualTo(Long value) {
            addCriterion("active_expenses >=", value, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesLessThan(Long value) {
            addCriterion("active_expenses <", value, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesLessThanOrEqualTo(Long value) {
            addCriterion("active_expenses <=", value, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesIn(List<Long> values) {
            addCriterion("active_expenses in", values, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesNotIn(List<Long> values) {
            addCriterion("active_expenses not in", values, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesBetween(Long value1, Long value2) {
            addCriterion("active_expenses between", value1, value2, "activeExpenses");
            return (Criteria) this;
        }

        public Criteria andActiveExpensesNotBetween(Long value1, Long value2) {
            addCriterion("active_expenses not between", value1, value2, "activeExpenses");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_spread_day
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_spread_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}