package com.southwind.frigga.dal.mybatis.model;

public class ChannelUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.qd_login
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String qdLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.qd_password
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String qdPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.qd_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String qdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.spread_price
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Double spreadPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.bank_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.bank_account
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.bank_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String bankUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.id
     *
     * @return the value of channel_user.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.id
     *
     * @param id the value for channel_user.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.qd_login
     *
     * @return the value of channel_user.qd_login
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getQdLogin() {
        return qdLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.qd_login
     *
     * @param qdLogin the value for channel_user.qd_login
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setQdLogin(String qdLogin) {
        this.qdLogin = qdLogin == null ? null : qdLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.qd_password
     *
     * @return the value of channel_user.qd_password
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getQdPassword() {
        return qdPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.qd_password
     *
     * @param qdPassword the value for channel_user.qd_password
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setQdPassword(String qdPassword) {
        this.qdPassword = qdPassword == null ? null : qdPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.qd_name
     *
     * @return the value of channel_user.qd_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getQdName() {
        return qdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.qd_name
     *
     * @param qdName the value for channel_user.qd_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setQdName(String qdName) {
        this.qdName = qdName == null ? null : qdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.spread_price
     *
     * @return the value of channel_user.spread_price
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Double getSpreadPrice() {
        return spreadPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.spread_price
     *
     * @param spreadPrice the value for channel_user.spread_price
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setSpreadPrice(Double spreadPrice) {
        this.spreadPrice = spreadPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.bank_name
     *
     * @return the value of channel_user.bank_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.bank_name
     *
     * @param bankName the value for channel_user.bank_name
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.bank_account
     *
     * @return the value of channel_user.bank_account
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.bank_account
     *
     * @param bankAccount the value for channel_user.bank_account
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.bank_user
     *
     * @return the value of channel_user.bank_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.bank_user
     *
     * @param bankUser the value for channel_user.bank_user
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }
}