package com.southwind.frigga.dal.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class RevenueExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public RevenueExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAdIdIsNull() {
			addCriterion("ad_id is null");
			return (Criteria) this;
		}

		public Criteria andAdIdIsNotNull() {
			addCriterion("ad_id is not null");
			return (Criteria) this;
		}

		public Criteria andAdIdEqualTo(Long value) {
			addCriterion("ad_id =", value, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdNotEqualTo(Long value) {
			addCriterion("ad_id <>", value, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdGreaterThan(Long value) {
			addCriterion("ad_id >", value, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ad_id >=", value, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdLessThan(Long value) {
			addCriterion("ad_id <", value, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdLessThanOrEqualTo(Long value) {
			addCriterion("ad_id <=", value, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdIn(List<Long> values) {
			addCriterion("ad_id in", values, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdNotIn(List<Long> values) {
			addCriterion("ad_id not in", values, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdBetween(Long value1, Long value2) {
			addCriterion("ad_id between", value1, value2, "adId");
			return (Criteria) this;
		}

		public Criteria andAdIdNotBetween(Long value1, Long value2) {
			addCriterion("ad_id not between", value1, value2, "adId");
			return (Criteria) this;
		}

		public Criteria andStartDayIsNull() {
			addCriterion("start_day is null");
			return (Criteria) this;
		}

		public Criteria andStartDayIsNotNull() {
			addCriterion("start_day is not null");
			return (Criteria) this;
		}

		public Criteria andStartDayEqualTo(String value) {
			addCriterion("start_day =", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayNotEqualTo(String value) {
			addCriterion("start_day <>", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayGreaterThan(String value) {
			addCriterion("start_day >", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayGreaterThanOrEqualTo(String value) {
			addCriterion("start_day >=", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayLessThan(String value) {
			addCriterion("start_day <", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayLessThanOrEqualTo(String value) {
			addCriterion("start_day <=", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayLike(String value) {
			addCriterion("start_day like", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayNotLike(String value) {
			addCriterion("start_day not like", value, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayIn(List<String> values) {
			addCriterion("start_day in", values, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayNotIn(List<String> values) {
			addCriterion("start_day not in", values, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayBetween(String value1, String value2) {
			addCriterion("start_day between", value1, value2, "startDay");
			return (Criteria) this;
		}

		public Criteria andStartDayNotBetween(String value1, String value2) {
			addCriterion("start_day not between", value1, value2, "startDay");
			return (Criteria) this;
		}

		public Criteria andEndDayIsNull() {
			addCriterion("end_day is null");
			return (Criteria) this;
		}

		public Criteria andEndDayIsNotNull() {
			addCriterion("end_day is not null");
			return (Criteria) this;
		}

		public Criteria andEndDayEqualTo(String value) {
			addCriterion("end_day =", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayNotEqualTo(String value) {
			addCriterion("end_day <>", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayGreaterThan(String value) {
			addCriterion("end_day >", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayGreaterThanOrEqualTo(String value) {
			addCriterion("end_day >=", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayLessThan(String value) {
			addCriterion("end_day <", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayLessThanOrEqualTo(String value) {
			addCriterion("end_day <=", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayLike(String value) {
			addCriterion("end_day like", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayNotLike(String value) {
			addCriterion("end_day not like", value, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayIn(List<String> values) {
			addCriterion("end_day in", values, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayNotIn(List<String> values) {
			addCriterion("end_day not in", values, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayBetween(String value1, String value2) {
			addCriterion("end_day between", value1, value2, "endDay");
			return (Criteria) this;
		}

		public Criteria andEndDayNotBetween(String value1, String value2) {
			addCriterion("end_day not between", value1, value2, "endDay");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeIsNull() {
			addCriterion("generate_time is null");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeIsNotNull() {
			addCriterion("generate_time is not null");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeEqualTo(String value) {
			addCriterion("generate_time =", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeNotEqualTo(String value) {
			addCriterion("generate_time <>", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeGreaterThan(String value) {
			addCriterion("generate_time >", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("generate_time >=", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeLessThan(String value) {
			addCriterion("generate_time <", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeLessThanOrEqualTo(String value) {
			addCriterion("generate_time <=", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeLike(String value) {
			addCriterion("generate_time like", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeNotLike(String value) {
			addCriterion("generate_time not like", value, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeIn(List<String> values) {
			addCriterion("generate_time in", values, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeNotIn(List<String> values) {
			addCriterion("generate_time not in", values, "generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeBetween(String value1, String value2) {
			addCriterion("generate_time between", value1, value2,
					"generateTime");
			return (Criteria) this;
		}

		public Criteria andGenerateTimeNotBetween(String value1, String value2) {
			addCriterion("generate_time not between", value1, value2,
					"generateTime");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(Double value) {
			addCriterion("money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(Double value) {
			addCriterion("money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(Double value) {
			addCriterion("money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(Double value) {
			addCriterion("money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(Double value) {
			addCriterion("money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<Double> values) {
			addCriterion("money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<Double> values) {
			addCriterion("money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(Double value1, Double value2) {
			addCriterion("money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(Double value1, Double value2) {
			addCriterion("money not between", value1, value2, "money");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table revenue
	 * @mbggenerated  Sat Sep 13 19:27:34 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table revenue
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}