package com.southwind.frigga.dal.mybatis.model;

public class Revenue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.ad_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Long adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.start_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String startDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.end_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String endDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.generate_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private String generateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.money
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.id
     *
     * @return the value of revenue.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.id
     *
     * @param id the value for revenue.id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.ad_id
     *
     * @return the value of revenue.ad_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Long getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.ad_id
     *
     * @param adId the value for revenue.ad_id
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setAdId(Long adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.start_day
     *
     * @return the value of revenue.start_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getStartDay() {
        return startDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.start_day
     *
     * @param startDay the value for revenue.start_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setStartDay(String startDay) {
        this.startDay = startDay == null ? null : startDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.end_day
     *
     * @return the value of revenue.end_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getEndDay() {
        return endDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.end_day
     *
     * @param endDay the value for revenue.end_day
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setEndDay(String endDay) {
        this.endDay = endDay == null ? null : endDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.generate_time
     *
     * @return the value of revenue.generate_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public String getGenerateTime() {
        return generateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.generate_time
     *
     * @param generateTime the value for revenue.generate_time
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setGenerateTime(String generateTime) {
        this.generateTime = generateTime == null ? null : generateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.money
     *
     * @return the value of revenue.money
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.money
     *
     * @param money the value for revenue.money
     *
     * @mbggenerated Mon Aug 25 19:46:55 GMT+08:00 2014
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}